import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/mainpage">MainPage</Link>
        </li>
        <li>
          <Link to="/login">Login</Link>
        </li>
        <li>
          <Link to="/halamankonfigurasi">HalamanKonfigurasi</Link>
        </li>
        <li>
          <Link to="/monitoringriwayat">MonitoringRiwayat</Link>
        </li>
        <li>
          <Link to="/profile">Profile</Link>
        </li>
        <li>
          <Link to="/contactpage">ContactPage</Link>
        </li>
        <li>
          <Link to="/fourhundredfour">FourHundredFour</Link>
        </li>
        <li>
          <Link to="/register">Register</Link>
        </li>
        <li>
          <Link to="/halamankonfigurasitdklogin">
            HalamanKonfigurasiTdkLogin
          </Link>
        </li>
        <li>
          <Link to="/monitoringriwayattdklogin">MonitoringRiwayatTdkLogin</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
